### PR TITLE
Master

### PR DESCRIPTION
**Pull request by vanderhey**

### CODE REVIEW

**Comment by JakeLardinois** [comment]
Eric,
Go ahead and make the changes per my comments (commit and sync) and then write me a message here so I can review them...

**Comment by vanderhey** [comment]
Jake,
I made the changes per your comments.

**Comment by JakeLardinois** [comment]
Eric,
                I merged your code and then made some adjustments to the Employee Class.  Check them out…

**Comment by vanderhey** [comment]
Excellent that’s nice and clean. It will be nice when I can code this way.

**Pull request merged**
